-- Do lua filetype detection
vim.g.do_filetype_lua = 1

require('plugins')
require('settings')
require('options')
require('mappings')
require('autocmds')
require('globals')
require('conf/nvim-treesitter')
require('conf/nvim-lsp-installer')
-- require('conf/lspsaga')
require('conf/diagnostics')
require('conf/formatter')
require('conf/bufferline')
require('conf/toggleterm')
require('conf/nvim-cmp')
require('conf/telescope')
require('conf/heirline')
require('conf/indent-blankline')
require('conf/package-info')
require('conf/gitsigns')
require('conf/color-converter')
require('conf/nvim-tree')
require('conf/project')
require('conf/emmet')
require('colorscheme')
